name: Run PowerShell Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  powershell-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a PowerShell script
        shell: pwsh
        run: |
          Write-Output "Current Date and Time:"
          Get-Date
          Write-Output "Listing files in the repo:"
          Get-ChildItem
